version: '3'
services:
  earthdb:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=earth
    volumes:
      - ./dataset-earth:/docker-entrypoint-initdb.d
    ports:
      - 5434:5432
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: ['start-dev', '--import-realm']
    restart: unless-stopped
    environment:
      KC_LOG_LEVEL: INFO
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    ports:
      - 8080:8080
    volumes:
      - ./realms/realm-import.json:/opt/keycloak/data/import/realm.json:ro
