services:
  admin:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    env_file: '.env'
    #    user: ${UID}:${GID}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/api/hello']
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ${REAL_SITE}:/website
    ports:
      - '4000:4000'
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nautica
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nautica
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nautica -d nautica']
      interval: 10s # how often to run the check
      timeout: 5s # how long to wait for each check
      retries: 5 # how many times to retry before marking unhealthy
      start_period: 15s # give Postgres time to boot before starting checks
volumes:
  postgres_data:
